name: iptv_zb

on:
  schedule:
    - cron: '0 7,20 * * *'  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   
    
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: 获取酒店源
        run: |
          cd $GITHUB_WORKSPACE
          python ./iptv_zb.py
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yt-dlp sed nmap
        
      - name: 检测组播源
        run: |
          cd $GITHUB_WORKSPACE
          cat zubo.txt > zubo_备份.txt
          bash ./zubo2.sh
          cat txt/广东电信.txt txt/北京联通.txt txt/四川电信.txt txt/湖南电信.txt txt/广东联通.txt txt/湖北电信.txt txt/浙江电信.txt txt/江苏电信.txt txt/河南电信.txt txt/河北联通.txt > zubo.txt
          
      - name: 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "更新直播源"
          # git commit *.m3u -m "Add generated file"
          #git pull --rebase

      - name: Push To Gitee
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GE_TOKEN }}
          repository: ${{ secrets.GE_PATH }}
          directory: .
          branch: iptv
          force: true
          github_url: https://gitee.com

      - name: Push To Github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          repository: ${{ secrets.GH_PATH }}
          directory: .
          force: true
          