name: 测试光迅ip
on:
#  schedule:
#    - cron: 30 10 */3 * *
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
  
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp sed nmap
    
    - name: 筛选ip
      run: |
        cd $GITHUB_WORKSPACE
        bash ./test.sh
        
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install selenium requests futures eventlet

    - name: run iptvpy
      run: python ${{ github.workspace }}/test_gxtv.py
      
    - name: 提交更新
      run: |
        cd $GITHUB_WORKSPACE
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "更新光迅ip"
        git push
