name: zb

on:
  schedule:
    - cron: '0 4,19 * * *'  # 每12个小时的第 0 分钟运行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install bs4 playwright requests
          playwright install
          pip install datetime

      - name: 获取组播地址
        run: |
          cd $GITHUB_WORKSPACE
          python ./zubo.py
          bash ./合并.sh
          python ./去重.py
    
      - name: 提交更改
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit *.txt -m "更新组播源"
          # git commit *.m3u -m "Add generated file"
          #git pull --rebase

      - name: Push To Gitee
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GE_TOKEN }}
          repository: ${{ secrets.GE_PATH }}
          directory: .
          branch: iptv
          force: true
          github_url: https://gitee.com

      - name: Push To Github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          repository: ${{ secrets.GH_PATH }}
          directory: .
          force: true