name: zubo

on:
#  schedule:
#    - cron: 5 9 * * *
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
  
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp sed nmap
      
    - name: Run Multitest Script
#      working-directory: iptv
      run: |
        cd $GITHUB_WORKSPACE
        bash ./multi_test_2.sh

    - name: 提交更改
      run: |
        cd $GITHUB_WORKSPACE
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update results"
        git push
