name: zubo

on:
  schedule:
    - cron: '20 8,23 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   
      
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y yt-dlp sed nmap
        
      - name: 获取测试组播源
        run: |
          cd $GITHUB_WORKSPACE
          cat zubo.txt > zubo_备份.txt
          bash ./zubo2.sh
          cat iptv.txt zubo2.txt > iptv.txt
          rm -f zubo2.txt
      
      - name: 更新组播源
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "更新组播源"
          #git push
      - name: Push To Gitee
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GE_TOKEN }}
          repository: ${{ secrets.GE_PATH }}
          directory: .
          branch: iptv
          force: true
          github_url: https://gitee.com

      - name: Push To Github
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          repository: ${{ secrets.GH_PATH }}
          directory: .
          force: true
