name: zubo

on:
#  schedule:
#    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0   
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp sed nmap
        
    - name: 测试组播地址
      run: |
        cd $GITHUB_WORKSPACE
        bash ./zubo2.sh
      
    - name: 更新组播源
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "更新组播源"
        git push
