name: zubo

on:
  schedule:
    - cron: '0 5,14 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
      run: pip3 install bs4 playwright requests     
      run: playwright install
      run: pip install datetime

    - name: Run py
      run: python ${{ github.workspace }}/zubo.py
      
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y yt-dlp sed nmap
      
    - name: 获取组播地址
      run: |
        cd $GITHUB_WORKSPACE
        bash ./zubo2.sh

#    - name: 测试组播地址
#      run: |
#        cd $GITHUB_WORKSPACE
#        chmod +x speed.sh
#        bash ./zubo.sh

    - name: run 去重py
      run: python ${{ github.workspace }}/去重.py
      
    - name: 更新组播源
      run: |
        cd $GITHUB_WORKSPACE
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "更新组播源"
        git push
